# https://github.com/atom/ci

language: generic

os:
  - linux
  - osx

install:
  - |
    if [ "$TRAVIS_OS_NAME" = 'osx' ]; then
      brew cask install mactex-no-gui
      brew tap nwhetsell/lilypond
      brew install lilypond
      brew unlink guile
      brew link --force guile@1
    else
      sudo apt-get --assume-yes install lilypond
    fi

script: curl --show-error --silent https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh
