# https://github.com/atom/ci

language: generic

os:
  - linux
  - osx

install:
  - |
    if [ $TRAVIS_OS_NAME = 'linux' ]; then
      sudo apt-get --assume-yes install lilypond
    elif [ $TRAVIS_OS_NAME = 'osx' ]; then
      brew cask install lilypond
    fi
  - |
    lilypond - <<EOS
      { c' }
    EOS

before_script: |
  mkdir grammars
  echo '{name: "LilyPond", scopeName: "source.lilypond", fileTypes: ["ly"]}' > grammars/lilypond.cson

script: curl --show-error --silent https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh
