name: CI

on: [push, pull_request]

jobs:
  Test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        lilypond-version: [2.26.0]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Check out repository
      uses: actions/checkout@v6

    - name: Install Pulsar dependencies on Linux
      run: sudo apt install -y libsecret-1-0
      if: ${{ matrix.os == 'ubuntu-latest' }}

    - name: Install Pulsar on Linux
      uses: pulsar-edit/action-pulsar-dependency@v3
      if: ${{ matrix.os == 'ubuntu-latest' }}
    - name: Install Pulsar on macOS
      run: brew install pulsar
      if: ${{ matrix.os == 'macos-latest' }}

    - name: Install LilyPond on Linux
      run: |
        wget --no-verbose https://gitlab.com/lilypond/lilypond/-/releases/v${{ matrix.lilypond-version }}/downloads/lilypond-${{ matrix.lilypond-version }}-linux-x86_64.tar.gz
        tar -xf lilypond-${{ matrix.lilypond-version }}-linux-x86_64.tar.gz
        echo "$(pwd)/lilypond-${{ matrix.lilypond-version }}/bin" >> $GITHUB_PATH
      if: ${{ matrix.os == 'ubuntu-latest' }}
    - name: Install LilyPond on macOS
      run: brew install lilypond
      if: ${{ matrix.os == 'macos-latest' }}

    - name: Install package dependencies
      run: ppm install

    - name: Run tests
      uses: coactions/setup-xvfb@v1
      with:
        run: pulsar --test spec
